### PR TITLE
feat: add generating item history using AI

### PR DESCRIPTION
**Pull request by ktos**

### CODE REVIEW

**Comment by ktos** [comment]
Generating of item history using AI is now behind a feature flag which must be set in `appsettings.json`, e.g.:

```
"FeatureFlags": {
  "UseAI": true
}
```

**Comment by ktos** [comment]
DO NOT MERGE YET!

Still - if there is no secrets configuration, the AIProvider cannot be constructed and throws. How should we proceed?

**Comment by purifetchi** [comment]
> DO NOT MERGE YET!
> 
> Still - if there is no secrets configuration, the AIProvider cannot be constructed and throws. How should we proceed?
> 
> We should not use FeatureManagement in a constructor (as it is async), and we cannot register services based on features? I am not sure.

you actually can use featuremanagement outside a service scope: https://stackoverflow.com/questions/61659144/how-to-get-featuremanager-in-configureservices

we'd just have to manually create the feature manager class and pass to it our config file

**Comment by ktos** [comment]
Additionally, codestral suggested me something which may be even better:

```csharp
public static class FeatureFlagServiceExtension
{
    public static IServiceCollection AddTransientIfFeatureEnabled<TInterface, TImplementation>(this IServiceCollection services, string featureName) where TImplementation : class, TInterface
        => services.AddTransientIfFeatureEnabled(featureName, typeof(TInterface), typeof(TImplementation));

    public static IServiceCollection AddTransientIfFeatureEnabled(this IServiceCollection services, string featureName, Type serviceType, Type implementationType)
    {
        var featureManager = services.BuildServiceProvider().GetRequiredService<IFeatureManagerSnapshot>();

        if (featureManager[featureName].Value)
            return services.AddTransient(serviceType, implementationType);

        return services;
    }

    // Add similar methods for AddScoped and AddSingleton if needed...
}
```

So it should be used something like:

```csharp
services.AddSingletonIfFeatureEnabled<IMyService, MyService>("MyFeatureFlag");
```

Not sure if it is more readable than current version.

**Comment by purifetchi** [comment]
> Additionally, codestral suggested me something which may be even better:
> 
> ```cs
> public static class FeatureFlagServiceExtension
> {
>     public static IServiceCollection AddTransientIfFeatureEnabled<TInterface, TImplementation>(this IServiceCollection services, string featureName) where TImplementation : class, TInterface
>         => services.AddTransientIfFeatureEnabled(featureName, typeof(TInterface), typeof(TImplementation));
> 
>     public static IServiceCollection AddTransientIfFeatureEnabled(this IServiceCollection services, string featureName, Type serviceType, Type implementationType)
>     {
>         var featureManager = services.BuildServiceProvider().GetRequiredService<IFeatureManagerSnapshot>();
> 
>         if (featureManager[featureName].Value)
>             return services.AddTransient(serviceType, implementationType);
> 
>         return services;
>     }
> 
>     // Add similar methods for AddScoped and AddSingleton if needed...
> }
> ```
> 
> So it should be used something like:
> 
> ```cs
> services.AddSingletonIfFeatureEnabled<IMyService, MyService>("MyFeatureFlag");
> ```
> 
> Not sure if it is more readable than current version.

i actually like this one better!

**Review by purifetchi — APPROVED** [review]

**Pull request merged**
